# Generated by Django 5.2.17 on 2026-08-18 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=280, validators=[django.core.validators.MaxLengthValidator(280)])),
            ],
        ),
    ]
